export const BIST_HISSELER: { ticker: string; ad: string; domain?: string }[] = [
  { ticker: "A1CAP", ad: "A1 Capital" },
  { ticker: "ACSEL", ad: "Acıselsan" },
  { ticker: "ADEL", ad: "Adel Kalemcilik" },
  { ticker: "ADESE", ad: "Adese GYO" },
  { ticker: "ADGYO", ad: "Adra GYO" },
  { ticker: "AEFES", ad: "Anadolu Efes" },
  { ticker: "AFYON", ad: "Afyon Çimento" },
  { ticker: "AGESA", ad: "Agesa Hayat" },
  { ticker: "AGHOL", ad: "AG Anadolu Grubu" },
  { ticker: "AGROT", ad: "Agrotech" },
  { ticker: "AGYO", ad: "Atakule GYO" },
  { ticker: "AHGAZ", ad: "Ahlatcı Doğalgaz" },
  { ticker: "AKBNK", ad: "Akbank", domain: "akbank.com" },
  { ticker: "AKCNS", ad: "Akçansa" },
  { ticker: "AKFGY", ad: "Akfen GYO" },
  { ticker: "AKFYE", ad: "Akfen Yenilenebilir" },
  { ticker: "AKGRT", ad: "Aksigorta" },
  { ticker: "AKMGY", ad: "Akmerkez GYO" },
  { ticker: "AKSA", ad: "Aksa Akrilik" },
  { ticker: "AKSEN", ad: "Aksa Enerji" },
  { ticker: "AKSGY", ad: "Akiş GYO" },
  { ticker: "AKSUE", ad: "Aksu Enerji" },
  { ticker: "AKTIF", ad: "Aktif Yatırım Bankası" },
  { ticker: "ALARK", ad: "Alarko Holding" },
  { ticker: "ALBRK", ad: "Albaraka Türk" },
  { ticker: "ALCAR", ad: "Alcar Otomotiv" },
  { ticker: "ALCTL", ad: "Alcatel Lucent" },
  { ticker: "ALFAS", ad: "Alfa Solar" },
  { ticker: "ALGYO", ad: "Alarko GYO" },
  { ticker: "ALKIM", ad: "Alkim Kimya" },
  { ticker: "ALMAD", ad: "Altın Madeni" },
  { ticker: "ALTNY", ad: "Altınyağ" },
  { ticker: "ALVES", ad: "Alves Elektrik" },
  { ticker: "ANELE", ad: "Anel Elektrik" },
  { ticker: "ANGEN", ad: "Angen Biyoteknoloji" },
  { ticker: "ANHYT", ad: "Anadolu Hayat" },
  { ticker: "ANSGR", ad: "Anadolu Sigorta" },
  { ticker: "ARCLK", ad: "Arçelik", domain: "arcelik.com" },
  { ticker: "ARDYZ", ad: "Ardıç Yazılım" },
  { ticker: "ARENA", ad: "Arena Bilgisayar" },
  { ticker: "ARSAN", ad: "Arsan Tekstil" },
  { ticker: "ASELS", ad: "Aselsan" },
  { ticker: "ASTOR", ad: "Astor Enerji" },
  { ticker: "ASUZU", ad: "Anadolu Isuzu" },
  { ticker: "ATAGY", ad: "Ata GYO" },
  { ticker: "ATAKP", ad: "Atakaş Petrokimya" },
  { ticker: "ATEKS", ad: "Altınyıldız Tekstil" },
  { ticker: "ATLAS", ad: "Atlas Menkul" },
  { ticker: "AVGYO", ad: "Avrasya GYO" },
  { ticker: "AVHOL", ad: "Av Holding" },
  { ticker: "AVOD", ad: "A.V.O.D." },
  { ticker: "AYDEM", ad: "Aydem Enerji" },
  { ticker: "AYEN", ad: "Ayen Enerji" },
  { ticker: "AYES", ad: "Ayes Çelik" },
  { ticker: "AZTEK", ad: "Aztek Elektronik" },
  { ticker: "BAGFS", ad: "Bagfaş" },
  { ticker: "BAKAB", ad: "Bak Ambalaj" },
  { ticker: "BALAT", ad: "Balataş" },
  { ticker: "BANVT", ad: "Banvit" },
  { ticker: "BARMA", ad: "Barmani Madeni" },
  { ticker: "BASCM", ad: "Başkent Çimento" },
  { ticker: "BASGZ", ad: "Başkentgaz" },
  { ticker: "BERA", ad: "Bera Holding" },
  { ticker: "BEYAZ", ad: "Beyaz Filo" },
  { ticker: "BFREN", ad: "Bosch Fren" },
  { ticker: "BIGCH", ad: "Bigchef" },
  { ticker: "BIMAS", ad: "BİM Mağazalar", domain: "bim.com.tr" },
  { ticker: "BIOEN", ad: "Biotrend Enerji" },
  { ticker: "BIZIM", ad: "Bizim Toptan" },
  { ticker: "BJKAS", ad: "Beşiktaş" },
  { ticker: "BLCYT", ad: "Bilici Yatırım" },
  { ticker: "BMSTL", ad: "Borusan Mannesmann" },
  { ticker: "BNTAS", ad: "Bantaş" },
  { ticker: "BOBET", ad: "Boğaziçi Beton" },
  { ticker: "BOSSA", ad: "Bossa" },
  { ticker: "BRISA", ad: "Brisa", domain: "brisa.com.tr" },
  { ticker: "BRYAT", ad: "Borusan Yatırım" },
  { ticker: "BTCIM", ad: "Batıçimento" },
  { ticker: "BUCIM", ad: "Bursa Çimento" },
  { ticker: "BURCE", ad: "Burçelik" },
  { ticker: "BVSAN", ad: "Burçelik Vana" },
  { ticker: "BYDNR", ad: "Boyner Büyük Mağazacılık" },
  { ticker: "CANTE", ad: "Çan 2 Termik" },
  { ticker: "CASA", ad: "Casa GYO" },
  { ticker: "CCOLA", ad: "Coca-Cola İçecek", domain: "cci.com.tr" },
  { ticker: "CELHA", ad: "Çelik Halat" },
  { ticker: "CEMAS", ad: "Çemaş Döküm" },
  { ticker: "CEMTS", ad: "Çemtaş Çelik" },
  { ticker: "CIMSA", ad: "Çimsa" },
  { ticker: "CLEBI", ad: "Çelebi Hava" },
  { ticker: "CMBTN", ad: "Çimbeton" },
  { ticker: "COKAL", ad: "Çokal" },
  { ticker: "CRFSA", ad: "Carrefoursa", domain: "carrefoursa.com" },
  { ticker: "CVKMD", ad: "CVK Madencilik" },
  { ticker: "CWENE", ad: "CW Enerji" },
  { ticker: "DAGI", ad: "Dagi Giyim" },
  { ticker: "DAPGM", ad: "DAP GYO" },
  { ticker: "DENGE", ad: "Denge Yatırım" },
  { ticker: "DESA", ad: "Desa Deri" },
  { ticker: "DESPC", ad: "Despec" },
  { ticker: "DEVA", ad: "Deva Holding" },
  { ticker: "DGATE", ad: "Datagate" },
  { ticker: "DGGYO", ad: "Doğan GYO" },
  { ticker: "DITAS", ad: "Ditaş" },
  { ticker: "DMSAS", ad: "Demisaş Döküm" },
  { ticker: "DOAS", ad: "Doğuş Otomotiv", domain: "dogusotomotiv.com.tr" },
  { ticker: "DOHOL", ad: "Doğan Holding" },
  { ticker: "DOKTA", ad: "Döktaş" },
  { ticker: "DYOBY", ad: "DYO Boya" },
  { ticker: "DZGYO", ad: "Deniz GYO" },
  { ticker: "EBEBK", ad: "Ebebek" },
  { ticker: "ECILC", ad: "Eczacıbaşı İlaç" },
  { ticker: "ECZYT", ad: "Eczacıbaşı Yatırım" },
  { ticker: "EDATA", ad: "E-Data Teknoloji" },
  { ticker: "EGEEN", ad: "Ege Endüstri" },
  { ticker: "EGEPO", ad: "Ege Profil" },
  { ticker: "EGGUB", ad: "Ege Gübre" },
  { ticker: "EGSER", ad: "Ege Seramik" },
  { ticker: "EKGYO", ad: "Emlak Konut GYO" },
  { ticker: "EKSUN", ad: "Eksun Gıda" },
  { ticker: "EMKEL", ad: "Emek Elektrik" },
  { ticker: "ENERY", ad: "Enerya Enerji" },
  { ticker: "ENGYO", ad: "Enka GYO" },
  { ticker: "ENKAI", ad: "Enka İnşaat", domain: "enka.com" },
  { ticker: "ENTRA", ad: "Entra Enerji" },
  { ticker: "EPLAS", ad: "Ege Plast" },
  { ticker: "ERBOS", ad: "Erbosan" },
  { ticker: "EREGL", ad: "Ereğli Demir Çelik" },
  { ticker: "ERSU", ad: "Ersu Gıda" },
  { ticker: "ESCAR", ad: "Es-Car Kiralama" },
  { ticker: "ESCOM", ad: "Escom Gayrimenkul" },
  { ticker: "EUPWR", ad: "Europower Enerji" },
  { ticker: "FADE", ad: "Fade Gıda" },
  { ticker: "FENER", ad: "Fenerbahçe" },
  { ticker: "FLAP", ad: "Flap Kongre" },
  { ticker: "FONET", ad: "Fonet Bilgi" },
  { ticker: "FORMT", ad: "Formet Çelik" },
  { ticker: "FORTE", ad: "Forte Bilgi" },
  { ticker: "FROTO", ad: "Ford Otosan", domain: "fordotosan.com.tr" },
  { ticker: "GARAN", ad: "Garanti BBVA", domain: "garanti.com.tr" },
  { ticker: "GARFA", ad: "Garanti Faktoring" },
  { ticker: "GEDIK", ad: "Gedik Yatırım" },
  { ticker: "GENIL", ad: "Gen İlaç" },
  { ticker: "GENTS", ad: "Gentaş" },
  { ticker: "GESAN", ad: "Gestamp Sika" },
  { ticker: "GLRYH", ad: "Glory Holding" },
  { ticker: "GLYHO", ad: "Global Yatırım Holding" },
  { ticker: "GOLTS", ad: "Göltaş Çimento" },
  { ticker: "GOZDE", ad: "Gözde Girişim" },
  { ticker: "GSDHO", ad: "GSD Holding" },
  { ticker: "GSRAY", ad: "Galatasaray" },
  { ticker: "GUBRF", ad: "Gübre Fabrikaları" },
  { ticker: "GWIND", ad: "Galata Wind" },
  { ticker: "HALKB", ad: "Halkbank", domain: "halkbank.com.tr" },
  { ticker: "HATEK", ad: "Hateks" },
  { ticker: "HEKTS", ad: "Hektaş" },
  { ticker: "HLGYO", ad: "Halk GYO" },
  { ticker: "HOROZ", ad: "Horoz Lojistik" },
  { ticker: "HTTBT", ad: "Hattat Enerji" },
  { ticker: "HUBVC", ad: "Hub Venture" },
  { ticker: "HUNER", ad: "Hüner Enerji" },
  { ticker: "HURGZ", ad: "Hürriyet Gazetecilik" },
  { ticker: "ICBCT", ad: "ICBC Turkey Bank" },
  { ticker: "IHLAS", ad: "İhlas Holding" },
  { ticker: "IHLGM", ad: "İhlas Gazetecilik" },
  { ticker: "INDES", ad: "İndeks Bilgisayar" },
  { ticker: "INFO", ad: "İnfo Yatırım" },
  { ticker: "INVEO", ad: "İnveo" },
  { ticker: "IPEKE", ad: "İpek Doğal Enerji" },
  { ticker: "ISBIR", ad: "İşbir Holding" },
  { ticker: "ISCTR", ad: "İş Bankası C", domain: "isbank.com.tr" },
  { ticker: "ISFIN", ad: "İş Finansal Kiralama" },
  { ticker: "ISGYO", ad: "İş GYO" },
  { ticker: "ITTFK", ad: "İttifak Holding" },
  { ticker: "IZENR", ad: "İzmir Enerji" },
  { ticker: "IZMDC", ad: "İzmir Demir Çelik" },
  { ticker: "JANTS", ad: "Jantsa" },
  { ticker: "KAPLM", ad: "Kaplamin Ambalaj" },
  { ticker: "KAREL", ad: "Karel Elektronik" },
  { ticker: "KARSN", ad: "Karsan" },
  { ticker: "KARTN", ad: "Kartonsan" },
  { ticker: "KATMR", ad: "Katmerciler" },
  { ticker: "KAYSE", ad: "Kayseri Şeker" },
  { ticker: "KCHOL", ad: "Koç Holding" },
  { ticker: "KERVT", ad: "Kervan Gıda" },
  { ticker: "KFEIN", ad: "Kafein Yazılım" },
  { ticker: "KLGYO", ad: "Kiler GYO" },
  { ticker: "KLKIM", ad: "Kalekim" },
  { ticker: "KLNMA", ad: "Kalkınma Yatırım Bankası" },
  { ticker: "KNFRT", ad: "Konfrut" },
  { ticker: "KONYA", ad: "Konya Çimento" },
  { ticker: "KORDS", ad: "Kordsa" },
  { ticker: "KOZAA", ad: "Koza Anadolu" },
  { ticker: "KOZAL", ad: "Koza Altın" },
  { ticker: "KRDMA", ad: "Kardemir A" },
  { ticker: "KRDMB", ad: "Kardemir B" },
  { ticker: "KRDMD", ad: "Kardemir D" },
  { ticker: "KRSTL", ad: "Kristal Kola" },
  { ticker: "LIDER", ad: "Lider Faktoring" },
  { ticker: "LINK", ad: "Link Bilgisayar" },
  { ticker: "LKMNH", ad: "Lokman Hekim" },
  { ticker: "LMKDC", ad: "Limak Çimento" },
  { ticker: "LOGO", ad: "Logo Yazılım" },
  { ticker: "MAALT", ad: "Malt Sanayi" },
  { ticker: "MANAS", ad: "Manas Enerji" },
  { ticker: "MARKA", ad: "Marka GYO" },
  { ticker: "MARTI", ad: "Martı Otel" },
  { ticker: "MAVI", ad: "Mavi Giyim" },
  { ticker: "MEDTR", ad: "Meditera" },
  { ticker: "MEPET", ad: "Mepet Metro" },
  { ticker: "MERCN", ad: "Mercan Kimya" },
  { ticker: "MERIT", ad: "Merit Turizm" },
  { ticker: "MERKO", ad: "Merko Gıda" },
  { ticker: "METRO", ad: "Metro Ticaret" },
  { ticker: "MGROS", ad: "Migros", domain: "migros.com.tr" },
  { ticker: "MNDRS", ad: "Menderes Tekstil" },
  { ticker: "MOBTL", ad: "Mobil Telekom" },
  { ticker: "MOGAN", ad: "Mogan Teknoloji" },
  { ticker: "MPARK", ad: "MLP Sağlık", domain: "mlp.com.tr" },
  { ticker: "MRSHL", ad: "Marshall Boya" },
  { ticker: "MTRKS", ad: "Matriks Bilgi" },
  { ticker: "NATAS", ad: "Natas" },
  { ticker: "NATEN", ad: "Nate Enerji" },
  { ticker: "NETAS", ad: "Netaş Telekom" },
  { ticker: "NIBAS", ad: "Nibaş" },
  { ticker: "NTGAZ", ad: "Naturelgaz" },
  { ticker: "NUGYO", ad: "Nurol GYO" },
  { ticker: "NUHCM", ad: "Nuh Çimento" },
  { ticker: "ODAS", ad: "Odaş Elektrik" },
  { ticker: "ONCSM", ad: "Onur Sağlık" },
  { ticker: "ORGE", ad: "Orge Enerji" },
  { ticker: "OSTIM", ad: "Ostim Endüstriyel" },
  { ticker: "OTKAR", ad: "Otokar" },
  { ticker: "OYAKC", ad: "Oyak Çimento" },
  { ticker: "OYLUM", ad: "Oylum Sınai" },
  { ticker: "OZGYO", ad: "Özak GYO" },
  { ticker: "PAMEL", ad: "Pamel Yenilenebilir" },
  { ticker: "PARSN", ad: "Parsan" },
  { ticker: "PENTA", ad: "Penta Teknoloji" },
  { ticker: "PETKM", ad: "Petkim", domain: "petkim.com.tr" },
  { ticker: "PETUN", ad: "Pınar Et" },
  { ticker: "PGSUS", ad: "Pegasus", domain: "flypgs.com" },
  { ticker: "PINSU", ad: "Pınar Su" },
  { ticker: "PKART", ad: "Plastikkart" },
  { ticker: "PKENT", ad: "Petrokent Turizm" },
  { ticker: "POLHO", ad: "Polisan Holding" },
  { ticker: "PRDGS", ad: "Pardus Girişim" },
  { ticker: "QNBFB", ad: "QNB Finansbank" },
  { ticker: "QNBFL", ad: "QNB Finans Leasing" },
  { ticker: "RAYSG", ad: "Ray Sigorta" },
  { ticker: "RHEAG", ad: "Rhea Girişim" },
  { ticker: "ROYAL", ad: "Royal Halı" },
  { ticker: "RYSAS", ad: "Reysaş Lojistik" },
  { ticker: "SAFKR", ad: "Safkar Soğutma" },
  { ticker: "SAHOL", ad: "Sabancı Holding", domain: "sabanci.com" },
  { ticker: "SANEL", ad: "Sanel Elektrik" },
  { ticker: "SANKO", ad: "Sanko Pazarlama" },
  { ticker: "SARKY", ad: "Sarkuysan" },
  { ticker: "SASA", ad: "Sasa Polyester", domain: "sasa.com.tr" },
  { ticker: "SDTTR", ad: "SDT Uzay" },
  { ticker: "SEKUR", ad: "Sekuro Plastik" },
  { ticker: "SELEC", ad: "Selçuk Ecza" },
  { ticker: "SELGD", ad: "Selçuk Gıda" },
  { ticker: "SEYKM", ad: "Seyitler Kimya" },
  { ticker: "SISE", ad: "Şişecam" },
  { ticker: "SKTAS", ad: "Söktaş Tekstil" },
  { ticker: "SMART", ad: "Smart Güneş" },
  { ticker: "SNGYO", ad: "Sinpaş GYO" },
  { ticker: "SOKM", ad: "Şok Marketler", domain: "sokmarket.com.tr" },
  { ticker: "SUWEN", ad: "Süwen Tekstil" },
  { ticker: "TABGD", ad: "Tab Gıda" },
  { ticker: "TATGD", ad: "Tat Gıda" },
  { ticker: "TAVHL", ad: "TAV Havalimanları", domain: "tav.aero" },
  { ticker: "TBORG", ad: "Türk Tuborg" },
  { ticker: "TCELL", ad: "Turkcell", domain: "turkcell.com.tr" },
  { ticker: "THYAO", ad: "Türk Hava Yolları", domain: "turkishairlines.com" },
  { ticker: "TKFEN", ad: "Tekfen Holding" },
  { ticker: "TKNSA", ad: "Teknosa" },
  { ticker: "TMSN", ad: "Tümosan Motor" },
  { ticker: "TMPOL", ad: "Temapol" },
  { ticker: "TOASO", ad: "Tofaş Otomobil", domain: "tofas.com.tr" },
  { ticker: "TRCAS", ad: "Turcas Petrol" },
  { ticker: "TRGYO", ad: "Torunlar GYO" },
  { ticker: "TSPOR", ad: "Trabzonspor" },
  { ticker: "TTKOM", ad: "Türk Telekom", domain: "turktelekom.com.tr" },
  { ticker: "TTRAK", ad: "Türk Traktör" },
  { ticker: "TUKAS", ad: "Tukaş" },
  { ticker: "TUPRS", ad: "Tüpraş", domain: "tupras.com.tr" },
  { ticker: "TURSG", ad: "Türkiye Sigorta" },
  { ticker: "ULKER", ad: "Ülker Bisküvi", domain: "ulker.com.tr" },
  { ticker: "UMPAS", ad: "Umpaş Holding" },
  { ticker: "UNLU", ad: "Ünlü Menkul" },
  { ticker: "USAK", ad: "Uşak Seramik" },
  { ticker: "VAKBN", ad: "Vakıfbank", domain: "vakifbank.com.tr" },
  { ticker: "VAKKO", ad: "Vakko Tekstil" },
  { ticker: "VESBE", ad: "Vestel Beyaz Eşya" },
  { ticker: "VESTL", ad: "Vestel" },
  { ticker: "VKGYO", ad: "Vakıf GYO" },
  { ticker: "YATAS", ad: "Yataş" },
  { ticker: "YKBNK", ad: "Yapı Kredi", domain: "yapikredi.com.tr" },
  { ticker: "YKSLN", ad: "Yükselen Çelik" },
  { ticker: "YYAPI", ad: "Yüksel Yapı" },
  { ticker: "ZOREN", ad: "Zorlu Enerji" },
  { ticker: "ZRGYO", ad: "Ziraat GYO" },
];
