export const STOCK_LOGO_SLUGS: Record<string, string> = {
  ADEL: "adel-kalemcilik",
  AEFES: "anadolu-efes",
  AFYON: "afyon-cimento",
  AGYO: "atakule-gyo",
  AHGAZ: "ahlatci-dogalgaz",
  AKBNK: "akbank",
  AKCNS: "akcansa",
  AKFGY: "akfen-gyo",
  AKGRT: "aksigorta",
  AKMGY: "akmerkez-gyo",
  AKSA: "aksa-akrilik",
  AKSEN: "aksa-enerji",
  AKSGY: "akis-gyo",
  AKSUE: "aksu-enerji",
  ALARK: "alarko-holding",
  ALBRK: "albaraka-turk",
  ALKIM: "alkim-kimya",
  ANELE: "anel-elektrik",
  ANSGR: "anadolu-sigorta",
  ARCLK: "arcelik",
  ARENA: "arena-bilgisayar",
  ARSAN: "arsan-tekstil",
  ASELS: "aselsan",
  ASTOR: "astor-enerji",
  ASUZU: "anadolu-isuzu",
  ATAGY: "ata-gyo",
  ATLAS: "atlas",
  AYEN: "ayen-enerji",
  BAGFS: "bagfas",
  BAKAB: "bak-ambalaj",
  BANVT: "banvit",
  BERA: "bera-holding",
  BESLR: "kervan-gida",
  BEYAZ: "beyaz-filo",
  BIOEN: "biotrend",
  BLCYT: "bilici-yatirim",
  BMSTL: "borusan-mannesmann",
  BOSSA: "bossa",
  BUCIM: "bursa-cimento",
  BURCE: "burcelik",
  CASA: "casa",
  CELHA: "celik-halat",
  CEMAS: "cemas-dokum",
  CEMTS: "cemtas",
  CMBTN: "cimbeton",
  CWENE: "cw-enerji",
  DAGI: "dagi-giyim",
  DESA: "desa-deri",
  DEVA: "deva-holding",
  DMSAS: "demisas-dokum",
  DOAS: "dogus-otomotiv",
  DOHOL: "dogan-holding",
  DYOBY: "dyo-boya",
  DZGYO: "deniz-gyo",
  ECILC: "eczacibasi-ilac",
  ECZYT: "eczacibasi-yatirim",
  EDATA: "e-data-teknoloji",
  EGEEN: "ege-endustri",
  EGEPO: "ege-profil",
  EGGUB: "ege-gubre",
  EGSER: "ege-seramik",
  EKSUN: "eksun-gida",
  EMKEL: "emek-elektrik",
  ENERY: "enerya-enerji",
  ENKAI: "enka-insaat",
  ERBOS: "erbosan",
  ERSU: "ersu-gida",
  ESCAR: "escar",
  EUPWR: "europower-enerji",
  FADE: "fade-gida",
  FLAP: "flap-kongre",
  FORTE: "forte",
  FROTO: "ford-otosan",
  GARFA: "garanti-faktoring",
  GEDIK: "gedik-yatirim",
  GENIL: "gen-ilac",
  GENTS: "gentas",
  GOLTS: "goltas-cimento",
  GOZDE: "gozde-girisim",
  GSDHO: "gsd-holding",
  HEKTS: "hektas",
  HOROZ: "horoz",
  ICUGS: "rhea-girisim",
  IHLAS: "ihlas-holding",
  INDES: "indeks-bilgisayar",
  INFO: "info-yatirim",
  ISBIR: "isbir-holding",
  IZMDC: "izmir-demir-celik",
  KAREL: "karel-elektronik",
  KARTN: "kartonsan",
  KATMR: "katmerciler",
  KCHOL: "koc",
  KFEIN: "kafein-yazilim",
  KLGYO: "kiler",
  KONYA: "konya-cimento",
  KRSTL: "kristal-kola",
  LIDER: "lider-faktoring",
  LINK: "link-bilgisayar",
  LKMNH: "lokman-hekim",
  LOGO: "logo-yazilim",
  LRSHO: "ittifak-holding",
  MARKA: "marka",
  MARTI: "marti-otel",
  MAVI: "mavi-giyim",
  MERCN: "mercan-kimya",
  MERIT: "merit-turizm",
  MERKO: "merko-gida",
  METRO: "metro",
  MNDRS: "menderes-tekstil",
  MPARK: "mlp-saglik",
  MRSHL: "marshall-boya",
  NETAS: "netas-telekom",
  NTGAZ: "naturelgaz",
  NUGYO: "nurol",
  NUHCM: "nuh-cimento",
  ODAS: "odas",
  OTKAR: "otokar",
  OYAKC: "oyak-cimento",
  PARSN: "parsan",
  PENTA: "penta-teknoloji",
  PETKM: "petkim",
  PGSUS: "pegasus",
  PKART: "plastikkart",
  PKENT: "petrokent-turizm",
  POLHO: "polisan-holding",
  PRDGS: "pardus-girisim",
  QNBTR: "qnb-finansbank",
  RAYSG: "ray-sigorta",
  RYSAS: "reysas-lojistik",
  SAHOL: "sabanci-holding",
  SANKO: "sanko-pazarlama",
  SARKY: "sarkuysan",
  SASA: "sasa-polyester",
  SEKUR: "sekuro-plastik",
  SEYKM: "seyitler-kimya",
  SISE: "sisecam",
  SKTAS: "soktas",
  SUWEN: "suwen-tekstil",
  TABGD: "tab-gida",
  TATGD: "tat-gida",
  TAVHL: "tav-havalimanlari",
  TBORG: "turk-tuborg",
  TCELL: "turkcell",
  THYAO: "turk-hava-yollari",
  TKFEN: "tekfen",
  TRALT: "koza-altin",
  TRCAS: "turcas-petrol",
  TRENJ: "ipek-dogal-enerji",
  TTKOM: "turk-telekom",
  TTRAK: "turk-traktor",
  TUPRS: "tupras",
  TURSG: "turkiye-sigorta",
  ULKER: "ulker-biskuvi",
  USAK: "usak-seramik",
  VAKKO: "vakko-tekstil",
  VESBE: "vestel-beyaz-esya",
  VESTL: "vestel",
  YKSLN: "yukselen-celik",
  ZOREN: "zorlu-enerji",
  ZRGYO: "ziraat-gyo",
};

export function getStockLogoUrl(ticker: string, domain?: string) {
  const slug = STOCK_LOGO_SLUGS[ticker.toUpperCase()];

  if (slug) {
    return `https://s3-symbol-logo.tradingview.com/${slug}.svg`;
  }

  if (domain) {
    return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`;
  }

  return null;
}

export function getStockLogoSource(ticker: string, domain?: string) {
  if (STOCK_LOGO_SLUGS[ticker.toUpperCase()]) return "tradingview";
  if (domain) return "domain";
  return "fallback";
}
